# Generated by Django 4.2.7 on 2023-11-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ikuzo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='days',
            field=models.CharField(default=0, max_length=50, null=0),
            preserve_default=False,
        ),
    ]
