# Generated by Django 4.2.7 on 2023-11-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ikuzo', '0003_alter_registration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vehicleModel',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
