# Generated by Django 4.2.7 on 2023-11-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ikuzo', '0004_registration_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.CharField(default=0.09881422924901187, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='vehicleModel',
            field=models.CharField(max_length=200),
        ),
    ]
